---
- name: Install Nginx
  hosts: nginx
  remote_user: newsha400
  become: yes

  roles:
    - nginx

- name: Deploy App
  hosts: apps
  remote_user: newsha400
  become: yes

  roles:
    - nodejs

 
