---
- name: Install npm
  apt: name=npm state=present

- name: Install forever
  become: yes
  npm: 
    name: forever 
    global: yes

- name: Install git
  apt: name=git state=present

- name: Clone git repository
  git: 
    repo: https://github.com/newsha400/devops-test.git
    dest: /home/newsha400/devops-test

- name: Forever stopall
  remote_user: newsha400
  command: /usr/local/bin/forever stopall

- name: Forever start 
  remote_user: newsha400
  command: /usr/local/bin/forever start /home/newsha400/devops-test/index.js

