---
- name: Install npm
  apt: name=npm state=present

- name: Install pm2
  npm: 
    name: pm2 
    global: yes

- name: Install git
  apt: name=git state=present

- name: Clone git repository
  git: 
    rep: https://github.com/newsha400/devops-test.git
    dest: /home/newsha400

- name: Delete old pm2 process
  command: pm2 delete /home/newsha400/devops-test/index.js
  ignore_errors: yes

- name: Start pm2 process
  command: pm2 start /home/newsha400/devops-test/index.js

